---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: elastic
resources:
  - elasticsearch.yaml
  - kibana.yaml
  - certificate.yaml
  - route-elasticsearch.yaml
  - route-kibana.yaml
  - external-secrets/es-internal-users.yaml
  - external-secrets/es-secure-settings.yaml
  - external-secrets/kibana-encryption-keys.yaml
